---
- name: Create virtualenv root directory
  file:
    path: "{{ elastalert_venv_rootdir }}"
    owner: "{{ elastalert_user }}"
    group: "{{ elastalert_group }}"
    state: directory

- name: Establish venv and ensure pip is at least version
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: "{{ elastalert_venv_rootdir }}/venv"
    virtualenv_python: "{{ elastalert_venv_python }}"
  become: yes
  become_user: "{{ elastalert_user }}"
  with_items:
    - pip
    - setuptools

- name: Install elastalert into virtualenv
  pip:
    name: "elastalert{{ '2' if 2 <= (elastalert_version.split('.')[0] | int)  else '' }}"
    version: "{{ elastalert_version }}"
    virtualenv: "{{ elastalert_venv_rootdir }}/venv"
    virtualenv_python: "{{ elastalert_venv_python }}"
  become_user: "{{ elastalert_user }}"
  become: yes

- name: Install compatible elasticsearch pip library
  pip:
    name: elasticsearch
    version: "{{ elastalert_es_pip_version }}"
    virtualenv: "{{ elastalert_venv_rootdir }}/venv"
    virtualenv_python: "{{ elastalert_venv_python }}"
  become_user: "{{ elastalert_user }}"
  become: yes
